/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  gpc
 * Created: 21-mag-2016
 */

CREATE TABLE utenti(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo SMALLINT,
    nome VARCHAR(128),
    cognome VARCHAR(128),
    username VARCHAR(128),
    password VARCHAR(128)
);

CREATE TABLE prodotti(

    idProdotto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idUtente INTEGER,
    nome VARCHAR(128),
    linkFoto VARCHAR(128),
    descrizione VARCHAR(128),
    quantita INTEGER,
    prezzo REAL,
    FOREIGN KEY (idUtente) REFERENCES utenti(id)
);


CREATE TABLE saldo(
    idSaldo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utenteConto REAL,
    idUtente INTEGER,
    FOREIGN KEY (idUtente) REFERENCES utenti(id)
);


INSERT INTO utenti (id, tipo, nome, cognome, username, password)
VALUES (default, 1, 'Gian Piero', 'Cozzula', 'Gpiero','Gpiero'),
(default, 1, 'Claudia', 'Cozzula', 'Claudia','Claudia');

INSERT INTO utenti (id, tipo, nome, cognome, username, password)
VALUES (default, 2, 'Alice', 'Cozzula', 'Alice','Alice'),
VALUES (default, 2, 'Stefano', 'Cozzula', 'Stefano','Stefano');

INSERT INTO prodotti(idProdotto, idUtente, nome, descrizione, linkFoto, quantita, prezzo)
VALUES  (default,1, 'Marmellata di more','una marmellata di more','./img/marmellata.jpg',5,4.5),
        (default,1, 'Sciarpa in lana','una sciarpa in lana','./img/sciarpa.jpg',2,7.0),
        (default,2, 'Formaggio pecorino','del formaggio pecorino','./img/formaggio.jpeg',10,12.0),
        (default,2, 'Maglione in lana','un maglione in lana','./img/maglione.jpg',3,25.0),
        (default,2, 'Posacenere in legno','un posacenere in legno','./img/posacenere.jpg',1,11.0);

INSERT INTO saldo(idSaldo, utenteConto, idUtente)
VALUES  (default,26.7,1),
        (default,51.89,2),
        (default,123.7,3),
        (default,78.10,4);



